In [ ]:
Ans 1 =
A database is an organized collection of structured information, or data, typically stored electronically in
a computer system.
SQL databases are relational, and NoSQL databases are non-relational. SQL databases use structured query language (SQL)
and have a predefined schema. NoSQL databases have dynamic schemas for unstructured data. SQL databases are vertically s
calable, while NoSQL databases are horizontally scalable.

Ans 2 =
DDL statements are similar to a computer programming language for defining data structures, especially database schemas. Common examples of DDL statements include CREATE, ALTER, and DROP.
Today's databases incorporate DDL in any formal language that describes data, although it is considered a subset of SQL.
CREATE TABLE
The CREATE TABLE command creates a new table in the database.
ALTER TABLE
The ALTER TABLE command adds, deletes, or modifies columns in a table.
The ALTER TABLE command also adds and deletes various constraints in a table.
DROP TABLE
The DROP TABLE command deletes a table in the database.
TRUNCATE TABLE
The TRUNCATE TABLE command deletes the data inside a table, but not the table itself.
\\program\\
CREATE TABLE Persons (
    PersonID int,
    LastName varchar(255),
    FirstName varchar(255),
    Address varchar(255),
    City varchar(255)
);
ALTER TABLE Customers
ADD Email varchar(255);

ALTER TABLE Customers
DROP COLUMN Email;

DROP TABLE Shippers;
TRUNCATE TABLE Categories;
Ans 3 = 
A data manipulation language (DML) is a
family of computer languages including commands permitting users to manipulate data in a database.
INSERT − Insert data into a table.
UPDATE − Update existing data within a table.
DELETE − Delete records from a database table.

Ans 4 = 
DQL (Data Query Language) Command in SQL
DQL or data query language is to perform the query on the data inside the schema or object (ie table, index, view,
function, etc). Withthe help of a DQL query, we can get the data from the database to perform actions or operations 
like analyzing the data.
The SELECT command is used to query or retrieve data from a table in the database. It is used to retrieve a subset of records from one or more tables. The SELECT command can be used in various forms:

Syntax of SELECT command :

SELECT <column-list>FROM<table-name>;

·        Table-name is the name of the table from which the information is retrieved.

·        Column-list includes one or more columns from which data is retrieved.

-- select first_name from Customers table 
SELECT first_name
FROM Customers;

ANS 5 =
A primary key generally focuses on the uniqueness of the table. It assures the value in the specific column is unique.
A foreign key is generally used to build a relationship between the two tables. The table allows only one primary key.

Ans 6 =
\\PROGRAM FOR CONNECTING MYSQL TO PYTHON\\
import mysql.connector
mydb = mysql.connector.connect(
  host="localhost",
  user="abc",
  password="password"
)
print(mydb)
mycursor = mydb.cursor()
mycursor.execute("SHOW DATABASES")
for x in mycursor:
  print(x)

ANS 7 =
Order	Clause	Function
1	FROM	Tables are joined to get the base data.
2	WHERE	The base data is filtered.
3	GROUP BY	The filtered base data is grouped.
4	HAVING	The grouped base data is filtered.
5	SELECT	The final data is returned.
6	ORDER BY	The final data is sorted.
7	LIMIT	The returned data is limited to row count.