In [ ]:
Q1. Create a Pandas Series that contains the following data: 4, 8, 15, 16, 23, and 42. Then, print the series.
ANS = 
import pandas as pd
test= (4, 8, 15, 16, 23, 42)
# Creating empty series
ser = pd.Series(test)
 
print(ser)
//OUTPUT//
0     4
1     8
2    15
3    16
4    23
5    42
dtype: int64

Q2. Create a variable of list type containing 10 elements in it, and apply pandas.Series function on the
variable print it.
ANS =
import pandas as pd

people_list = ['Jon','Mark','Maria','Jill','Jack']

my_series = pd.Series(people_list)

print(my_series)
//output//
0      Jon
1     Mark
2    Maria
3     Jill
4     Jack
dtype: object

Q3. Create a Pandas DataFrame that contains the following data:
    
//program//
import pandas as pd
df = pd.read_excel("pandasassignment.xlsx")
df.head()
//output//

Name Age	Gender
0	Alice	25	Female
1	Bob	    30	Male
2	Claire	27	Female

Q4. What is ‘DataFrame’ in pandas and how is it different from pandas.series? Explain with an example.
ANS=
A Pandas DataFrame is a 2 dimensional data structure, like a 2 dimensional array, or a table with rows and columns.
DataFrame is a 2-dimensional labeled data structure with columns of potentially different types. You can think of 
it like a spreadsheet or SQL table, or a dict of Series objects. It is generally the most commonly used pandas object.

As noted in the table, a Pandas Series is a 1D array of data, but a single-column DataFrame is a 2D table with one column. 
The main distinction
between the two is this. For a single-column DataFrame, an index can be optional, but a Series has to have an index defined.

//PROGRAM//
import pandas as pd

data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

#load data into a DataFrame object:
df = pd.DataFrame(data)

print(df)
//OUTPUT//
   calories  duration
0       420        50
1       380        40
2       390        45


Q5. What are some common functions you can use to manipulate data in a Pandas DataFrame? Can
you give an example of when you might use one of these functions?

1) Manipulate Columns of pandas DataFrame
2) Manipulate Rows of pandas DataFrame
3) Replace Values in pandas DataFrame

1.READ DATA () We can read data in pandas data frame as read_csv(). Two most used data read formats are csv and excel. If we are reading
data in excel format, we can also give sheet names as follows. There are other less used options of other file types too.

2. Head and Tail()
To see the data frame we can use df.head(). Head returns the first rows, if no input is given it will always show above 5
rows. In contrast to see below rows, we can use df.tail().
3. Shape, Size and Info

Q6. Which of the following is mutable in nature Series, DataFrame, Panel?
ANS =
Data Frame	Two-dimensional array	Mutable
Panel	Three-dimensional array	Mutable 


Q7. Create a DataFrame using multiple Series. Explain with an example.

ANS= 
import pandas as pd
# Create pandas Series
courses = pd.Series(["Spark","PySpark","Hadoop"])
fees = pd.Series([22000,25000,23000])
discount  = pd.Series([1000,2300,1000])

# Combine two series.
df=pd.concat([courses,fees],axis=1)

# It also supports to combine multiple series.
df=pd.concat([courses,fees,discount],axis=1)
print(df)
//OUTPUT//
         0      1     2
0    Spark  22000  1000
1  PySpark  25000  2300
2   Hadoop  23000  1000

SyntaxError: invalid syntax (3976471492.py, line 1)